GoogleCloudPlatform/workflows-samples

src/connector_access_secret.workflows.json
src/connector_access_secret.workflows.yaml
src/connector_publish_pubsub.workflows.json
src/connector_publish_pubsub.workflows.yaml
src/connector_read_firestore.workflows.json
src/connector_read_firestore.workflows.yaml
src/connector_schedule_tasks.workflows.json
src/connector_schedule_tasks.workflows.yaml
src/connector_start_compute_engine.workflows.json
src/connector_start_compute_engine.workflows.yaml
src/connector_stop_compute_engine.workflows.json
src/connector_stop_compute_engine.workflows.yaml
src/connector_write_firestore.workflows.json
src/connector_write_firestore.workflows.yaml

Adds Connector Samples in YAML and JSON.

feat: add connector samples

---

src/http_get.workflows.yaml

Fix syntax error: change 'header' to 'headers'

---

src/error_retry_500.cloudworkflows.json
src/error_retry_500.cloudworkflows.yaml

Fixes indentation for workflows sample 500 error

fix: fix indentation for error 500 sample

---

validateFilenames.sh

Improves the Workflow filename test output by using a ✓ or ✗.
Example:
```
Validating filenames...
✓ ./connector_start_compute_engine.workflows.yaml
✓ ./step_switch_embedded.workflows.yaml
✓ ./http_get.workflows.yaml
✓ ./step_explicit.workflows.yaml
✓ ./step_implicit.workflows.yaml
✓ ./connect_run.workflows.yaml
✓ ./vars.workflows.yaml
✓ ./expression.workflows.yaml
✓ ./connect_functions.workflows.yaml
✓ ./connect_compute_engine.workflows.yaml
✓ ./connector_stop_compute_engine.workflows.yaml
✓ ./subworkflow.workflows.yaml
✓ ./connect_firestore_read.workflows.yaml
✓ ./quickstart.workflows.yaml
✓ ./connect_translate.workflows.yaml
✓ ./myFirstWorkflow.workflows.yaml
✓ ./connector_access_secret.workflows.yaml
✓ ./error_retry_500.workflows.yaml
✓ ./connector_read_firestore.workflows.yaml
✓ …
```

ci: improve file validation output

---

src/list.workflows.yaml

docs: add new sample to declare lists without map

docs: create list.workflows.yaml

---

src/list.workflows.json

docs: create list.workflows.json

---

src/dictionary.workflows.json
src/dictionary.workflows.yaml

docs: remove list assignments and rename to my_map

docs: remove list assignments and rename to my_map

---

src/error_retry_http_status.workflows.json
src/error_retry_http_status.workflows.yaml

docs: add duplicate file to fix conflict (cl/380853966)

docs: add duplicate file to fix conflict

---

src/connectors/connector_run.workflows.json

Link to related Dockerfile in docs TBD
Fixes: b/202002153

docs: Update image to more current one

---

src/dictionary.workflows.json
src/dictionary.workflows.yaml

Use example currently displayed in docs so that Sample Browser page will link accordingly

docs: update sample to sync with docs

---

src/loop_variables.workflows.json
src/loop_variables.workflows.yaml

docs: Add samples for variables in nested loops

---

src/quickstart.workflows.json
src/quickstart.workflows.yaml

docs: Sync with UI sample

---

.github/workflows/filename_check.yaml
.github/workflows/generate_json_pr.yaml
.github/workflows/generated_json_check.yaml

Track the latest stable Ubuntu.

testing: switch github actions to ubuntu-latest

---

.github/workflows/filename_check.yaml

Node.js is not used in validateFilenames.sh

testing: remove nodejs dependency from filename validate action

---

src/bigquery_pagetoken.workflows.json
src/bigquery_pagetoken.workflows.yaml

docs: Add new samples to paginate BigQuery results

---

src/connect_firestore_read.workflows.json
src/connect_firestore_read.workflows.yaml

bugfix: resolving syntax error in connect_firestore_read

---

src/connector_access_secret.workflows.yaml

chore: add comment to secret manager sample

---

src/parallel_aggregate.workflows.yaml
src/parallel_inline.workflows.yaml
src/parallel_operations.workflows.yaml
src/parallel_shared_variables.workflows.json
src/parallel_shared_variables.workflows.yaml

docs: update parallel step samples

---

src/parallel_operations.workflows.yaml

docs: update comment to sync with blog post

---

src/connectors/connector_forms.workflows.json
src/connectors/connector_forms.workflows.yaml

Generate Forms connector sample workflows

---

src/connectors/connector_sheets.workflows.json
src/connectors/connector_sheets.workflows.yaml

fix: create Sheets sample workflow

---

src/parallel_aggregate.workflows.json
src/parallel_aggregate.workflows.yaml

docs: remove null from loveslabourslostnull

---

src/iterate_for_in_http.workflows.json
src/iterate_for_in_http.workflows.yaml
src/iterate_for_range.workflows.json
src/iterate_for_range.workflows.yaml
src/iterate_for_range_http.workflows.json
src/iterate_for_range_http.workflows.yaml
src/iterate_googleapis_translate.workflows.json
src/iterate_googleapis_translate.workflows.yaml
src/iterate_list.workflows.json
src/iterate_list.workflows.yaml
src/iterate_map.workflows.json
src/iterate_map.workflows.yaml

docs: add existing iteration samples

---

src/bigquery_pagetoken.workflows.yaml

docs: change startQuery step to use bq endpoint jobs.insert

---

.github/CODEOWNERS

fixes: Update CODEOWNERS with correct team name

---

src/bigquery_pagetoken.workflows.yaml

chore: fix lint

---

src/connectors/connector_dataflow.workflows.json
src/connectors/connector_dataflow.workflows.yaml

fix: params for connector_dataflow YAML & JSON sample codes

---

src/connectors/connector_sheets.workflows.yaml

Noticed comments while working on b/245727719

docs: fix comments

---

src/connector_write_sheets.workflows.json
src/connector_write_sheets.workflows.yaml

docs: add write and move sheets connector samples

---

src/connectors/connector_bigquery.workflows.json
src/connectors/connector_bigquery.workflows.yaml
src/connectors/connector_cloudfunctions.workflows.json
src/connectors/connector_cloudfunctions.workflows.yaml
src/connectors/connector_cloudscheduler.workflows.json
src/connectors/connector_cloudscheduler.workflows.yaml
src/connectors/connector_cloudtasks.workflows.json
src/connectors/connector_cloudtasks.workflows.yaml
src/connectors/connector_firestore.workflows.json
src/connectors/connector_firestore.workflows.yaml
src/connectors/connector_storagetransfer.workflows.json
src/connectors/connector_storagetransfer.workflows.yaml
src/connectors/connector_translate.workflows.json
src/connectors/connector_translate.workflows.yaml
src/connectors/connector_workflows.workflows.json
src/connectors/connector_workflows.workflows.yaml

fix: Update to use inclusive language

---

.github/header-checker-lint.yml
.github/snippet-bot.yml
.github/sync-repo-settings.yaml
src/connectors/connector_forms.workflows.yaml
src/connectors/connector_integrations.workflows.yaml
src/connectors/connector_sheets.workflows.yaml
src/connectors/connector_transcoder.workflows.yaml

feat: add bots

---

.github/sync-repo-settings.yaml
.github/workflows/check_filename.yaml
.github/workflows/generate_json_pr.yaml
.github/workflows/validate_jsonschema.yaml
.github/workflows/validate_syntax.yaml
nightly.tests.cloudbuild.yaml
pr.tests.cloudbuild.yaml

chore: clean up github workflows

---

jsonschema/README.md

chore: update json schema readme

---

src/quickstart.workflows.json
src/quickstart.workflows.yaml

docs: change sample workflow

---

functions/datetime/README.md

Changed from python 3.7 to 3.8, 3.7 is no longer supported by Flask.

chore: Update README.md

---

.github/workflows/lint_yaml.yaml
.gitignore
functions/datetime/README.md
functions/datetime/main.py
functions/datetime/requirements.txt
src/myFirstWorkflow.workflows.json
src/myFirstWorkflow.workflows.yaml
src/step_conditional_weekend.workflows.json
src/step_conditional_weekend.workflows.yaml

* Update GCF function for best practices
* Remove broken (404) GCF function

fix: update datetime gcf

---

.github/workflows/periodic-reporter.yaml

chore: add nightly failure notifications

---

.github/workflows/periodic-reporter.yaml

fix: update notifier

---

src/error_retry_predicate.workflows.json
src/error_retry_predicate.workflows.yaml

docs: Write error map elements to log for custom predicate

---

.github/CODEOWNERS

Updates workflow codeowners based on current organization

fix: update code owner

---

src/http_post.workflows.json
src/http_post.workflows.yaml

docs: Fix step name

---

src/parallel_iteration.workflows.yaml

docs: Add comment at request of SWE

---

src/connectors/connector_storage.workflows.json
src/connectors/connector_storage.workflows.yaml

docs: URL-encode object name

---

src/connectors/connector_storage.workflows.json
src/connectors/connector_storage.workflows.yaml

Per comment #22 in b/371471777

docs: Change object_name to encoded_object_name
